# Generated by Django 4.2.5 on 2023-10-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_edit_post_body_field_to_rich_text_uploading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='base.tag'),
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='images')),
                ('link', models.URLField()),
                ('tags', models.ManyToManyField(null=True, to='base.tag')),
            ],
        ),
    ]
