version: '3'
services:
  service:
    build: nobodyas
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres-cont
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - /custom/mount:/var/lib/postgresql/data