version: '3'
services:
  service:
    build:
      context: ./nobodyas/
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./nobodyas:/opt/nobodyas
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres-cont
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - /custom/mount:/var/lib/postgresql/data